-- 1. Table
ALTER TABLE model_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE relations_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions_rules ENABLE ROW LEVEL SECURITY;