-- 1. Table
ALTER TABLE adam.model_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE adam.relations_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE adam.roles_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE adam.permissions_rules ENABLE ROW LEVEL SECURITY;